### ISSUE TITLE
Trocar entre servidores

### ISSUE THREAD

**Issue by sorrisosrs** [AvatarHurden/Tribal-Wars-Engine#2]
Com a versão 1.2 do TWE não é mais possível criar mundos personalizados, pois as informações dos mundos são baixadas automaticamente. Porem não existe até então a opção de alternar entre servidores, visto que o padrão é o servidor brasileiro não consigo obter as informações de outros servidores.

Gostaria de saber se esta opção será implementada na próxima versão.

E pedir para que se a resposta seja sim, o lançamento de um HotFix :)

PS: Ficou mt bom os alertas que tanto demoraram!

Grato.

**Comment by AvatarHurden** [comment]
Agora foi adicionada a opção de trocar entre os servidores. Tentei procurar uma lista atualizada dos servidores do TW, mas não consegui encontrar nada confiável. Assim, peguei a lista presente na página principal do Tribal Wars.
